version: '2'
services:
  config-server:
    image: maxbezko/tmx-config-server:chapter3
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:     "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "eagle_eye_local"
  license-service:
    image: maxbezko/tmx-license-service:chapter3
    ports:
      - "8080:8080"
    environment:
      PROFILE:              "default"
      CONFIGSERVER_URI:     "http://config-server:8888"
      CONFIGSERVER_PORT:    "8888"
      DATABASESERVER_PORT:  "5432"
      ENCRYPT_KEY:          "IMSYMMETRIC"