server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/,classpath:config/license-service
#          searchLocations: file:/home/maksym/Projects/microservices/spring-cloud-action/ch3-config/config-server/src/main/resources/config/license-service

#  cloud:
#    config:
#      server:
#      encrypt.enabled: false